### ISSUE TITLE
Autoware path plan failed

### ISSUE THREAD

**Issue by jiameixie** [lgsvl/simulator#1030]
I followed the instructions in https://www.lgsvlsimulator.com/docs/autoware-instructions/.   
The car doesn't move after I click 2D Pose Estimate and 2D Nav Goal.

1. The Vehicle mode and point raw status are error
2. All the plans are failed
Can anyone help me with it? Thanks.

![image](https://user-images.githubusercontent.com/50685847/94637934-5a555f00-030b-11eb-8af5-425f748265ec.png)
![image](https://user-images.githubusercontent.com/50685847/94637950-66d9b780-030b-11eb-85a5-0b0f0bc9b18e.png)
![image](https://user-images.githubusercontent.com/50685847/94637978-7d800e80-030b-11eb-819e-2d1d19586180.png)
![image](https://user-images.githubusercontent.com/50685847/94638012-94266580-030b-11eb-9e2f-8128a0221fd5.png)

**Comment by EricBoiseLGSVL** [comment]
@cyberphysicalrobotics do you know what is causing the issue?

**Comment by EricBoiseLGSVL** [comment]
@hadiTab adding you to ping @cyberphysicalrobotics

**Comment by hadiTab** [comment]
@jiameixie can you show what point on the map you are selecting as the destination? That error usually shows up if the destination you chose is not valid (i.e. Autoware can't find a path to the point when searching through the vector map).

Also, an annoying issue with the planner in Autoware is that if you send an invalid destination request you need to restart the node to try again, otherwise all subsequent requests also fail. So if you select a destination and you get that error message and want to try again, go back to the `Quick Start` tab in the runtime manager and deactivate and reactivate `Mission Planner`.

**Comment by jiameixie** [comment]
@hadiTab Thank you for explaining the relevant knowledge to me. I forget what direction I chose. Maybe it was invalid.
