### ISSUE TITLE
What preparation beforehand is needed for editing HD map of Shalun?

### ISSUE THREAD

**Issue by kotakky** [lgsvl/simulator#1051]
I'm studying the HD map's operation by tutorial.
I cannot understand the procedure of HD map's edition and so, I contact you.
I want to know what preparation beforehand is needed for editing HD map of Shalun that is defalt data ,and know about the procedure.
If possible, please tell me the video, youtube  etc… .

**Comment by luqiang21** [comment]
@kotakky You can follow tutorials here: https://www.lgsvlsimulator.com/docs/map-annotation/ to learn how to annotate each element in the map. Let me know if you have any other questions when reading the document.

**Comment by kotakky** [comment]
Thank you,luqiang21.
I cannot understand the procedures that are marked by red cycle in attached photo.

In order to annotate HD map ,is it needed that connecting autoware with lgsvl by clonning https://github.com/lgsvl/Autoware?

I downloaded lgsvlsimulator-windows-64-2020.06 , from https://github.com/lgsvl/simulator/releases/tag/2020.06.
![map_annotation](https://user-images.githubusercontent.com/45957491/95706857-fd569300-0c92-11eb-8813-1ce5de16c5b9.JPG)

**Comment by EricBoiseLGSVL** [comment]
@kotakky 
- Default layer is set in the Inspector panel in the Unity Editor.  All imported meshes default to this layer but in case a user changes this or imports a purchased asset that has changed this, we want the layer set to Default.
- Road meshes need a MeshCollider Unity component for physics to work in the simulation.  You can use any collider but we recommend mesh because it sets to the shape of the mesh.  Please read Unity docs on mesh collider [here](https://docs.unity3d.com/Manual/class-MeshCollider.html).
