### ISSUE TITLE
How to use Visual Studio BreakPoint to debug the Sensor Plugin in 2021.01 version

### ISSUE THREAD

**Issue by Jiaqing-Cao** [lgsvl/simulator#1392]
Hi LGSVL team,

In 2021.01 version, I see all sensors are used as plugins, we add the sensor into Assets\External\Sensors\ and use Unity to build the sensor, upload to cloud and download to use the sensor in the simulator.

My question is : How do I debug the sensor code like using Visual Studio BreakPoint attach to Unity? 

Ofcourse, adding logs in the sensor code could debug, but then every time we add/change logs, we need to go over the build->upload->download and run, especially the build will take a long time.

So is there a easy way to debug the Sensor Plugin in 2021.01 version?

**Comment by EricBoiseLGSVL** [comment]
Yes, great question. In the top menu Simulator -> Sensor Debug Mode will allow you to use break points or debug.logs without having to rebuild sensors.  You will also see logs indicating you are in sensor debug and what sensor was loaded.  Be sure to turn off when you are done because it's state is saved in Editor memory.
