### ISSUE TITLE
There are a few things that need to be fixed in 2d/3d ground truth for pedestrians.

### ISSUE THREAD

**Issue by yjkim1016** [lgsvl/simulator#1508]
Hello.
I am using LGSVl for pedestrian perception research. However, There are some big problem to use.
The height of pedestrians is not real value in 2d/3d ground truth. All of them are the same height, despite their different heights.
I hope it gets fixed asap

Thank you

**Comment by EricBoiseLGSVL** [comment]
@yjkim1016 Sorry we are missing a feature you need for your research.  Fortunately, we have been working on this.  Next release, we will let users create their own pedestrians outside simulator source. I'll see if I can add remove the default ground truth collider size and calculate from mesh bounds.  If you can't wait for these release, you can make edits to the source code yourself.

Each pedestrian gets created with a root object called PedestrianBase.prefab. On this prefab there is a component attached called PedestrianController.  In this code, you can see at line 214 we create a default Bounds with given size.  Instead of using that, you can get all child mesh objects and create the bounds size from that.  If you need reference, you can look at NPCController.cs line 339.

```
Bounds = new Bounds(transform.position, Vector3.zero);
foreach (Renderer renderer in allRenderers)
{
    Bounds.Encapsulate(renderer.bounds); // renderer.bounds is world space 
}
```

The last thing to do is move the SetGroundTruthBox() method after the mesh is spawned. So, in PedestrianManager.cs line 277 and 421 just move the call after 278 Instantiate() and 423 respectively. Hope this helps.
