### ISSUE TITLE
LGSVL and Open Simulation Interface (OSI)

### ISSUE THREAD

**Issue by ffzero1** [lgsvl/simulator#1554]
Hello, 

Does SVL simulator support open simulation interface (OSI) to work with test management tool such as ECU-Test?

Thanks!

**Comment by lemketron** [comment]
SVL Simulator does not support [OSI](https://www.asam.net/news-media/detail/news/bmw-transfers-open-simulation-interface-osi-to-asam/). SVL Simulator was designed for real time simulation and thus sensors are very tightly coupled with the core simulator (though built as separate plug-ins) for high performance and frame rate when simulating complex sensor sets.

Because SVL Simulator is open source and extensible through many plug-in APIs as well as the Python API, it's possible that someone could create an interface between OSI and SVL but I'm not aware of anyone who has done so.

**Comment by ffzero1** [comment]
Thank you for the answer.
