### ISSUE TITLE
Can't build 2021.2 version

### ISSUE THREAD

**Issue by duongtran11** [lgsvl/simulator#1574]
I just cloned release-2021.2 from github
Trying to build it from source. Link it to cloud. Create a new cluster
![Untitled](https://user-images.githubusercontent.com/67900559/125267864-6312a100-e331-11eb-9430-b3066ce1c62c.png)
But Simulator Version is empty
Then I got these errors
![sdf](https://user-images.githubusercontent.com/67900559/125268651-17acc280-e332-11eb-9a2c-d5e9ce0faddb.png)
Seems like the simulator version I built was not 2021.2 although I cloned release-2021.2

**Comment by EricBoiseLGSVL** [comment]
We have an issue with users running binaries they built.  We are making fixes right now and should release soon.

**Comment by duongtran11** [comment]
> We have an issue with users running binaries they built. We are making fixes right now and should release soon.

Thank you!

**Comment by zelenkovsky** [comment]
This issue is supposed to be fixed by now. Could you please confirm and close this issue?

**Comment by duongtran11** [comment]
I got it running but one more question:
Why does WebUI still not recognize the new cluster I created ("2021.2?" in the picture) as 2021.2 version? Since I built 2021.2 simulator then link it to cloud then created that cluster "2021.2?", the cluster version supposes to be 2021.2, isn't it?
![Screenshot from 2021-07-14 08-51-57](https://user-images.githubusercontent.com/67900559/125548756-4b780cee-3b1e-4957-bee6-9612d5b036be.png)
Beside that, I couldn't add this simulator to 2021.2 cluster I created before ("cluster_moi" in the picture) with the standalone ready-to-run simulator I cloned from github (not the one I build)
![Screenshot from 2021-07-14 09-24-55](https://user-images.githubusercontent.com/67900559/125551128-8be6fdc9-2d82-405a-979b-50e0ff620c67.png)

**Comment by EricBoiseLGSVL** [comment]
Because the version you have made is no longer 2021.2.  You have made a custom binary and since users can change anything they want, it is not 2021.2.  This last release was rough because we are trying to make it easier for users to have compatibility but also restrict in webui instead of errors in simulator.
You can't add to cluster_moi because it had the same sim_id from the data_path.  If you change the path for binaries and editor, you can have more clusters active.
