### ISSUE TITLE
Reset Ego or NPC position in Python

### ISSUE THREAD

**Issue by risk-v** [lgsvl/simulator#1822]
Hi everyone,

I was wondering if it's possible to restart the position of an ego vehicle or an NPC after adding them to the scene  using the method sim.add_agent(). I tried sim.reset() and respawning everything again and it works but... Is this the most optimum way in terms of memory usage? Thanks in advance.

**Comment by EricBoiseLGSVL** [comment]
You can also use agent/set/state.

We recommend using reset because it sends analysis data back to the webui.  It's not the best in memory management but since we use prefabs, it isn't a large memory hit.  This also resets timers which is very important.  Lastly, reset is used because AD stacks don't like warping to positions and will fail.
