### ISSUE TITLE
Simulator error "Bad Gateway"

### ISSUE THREAD

**Issue by JordanCrawfordx** [lgsvl/simulator#1940]
Hello,
 
I'm trying to run a simulation but there seems to be an error with the gateway. Every time I run, the error message shows. Here's the error:

<html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.20.1</center> </body> </html>      

Also, I'm unable to view the image of my simulation as shown here: 

![SharedScreenshot](https://user-images.githubusercontent.com/94921943/148424430-9117391c-7a1d-44fc-b280-02c0a997525a.jpg)

@EricBoiseLGSVL If you could help, it'd be greatly appreciated! :)

**Comment by EricBoiseLGSVL** [comment]
Looks like an issue with your map, you should have a view of the scene instead of the generic image.  Please post the playerlog and screen shots of the map hierarchy panel in Unity.  Also, any errors you get when building it.
FYI windows 11 users have been reporting issues with simulator.  It is not officially supported.

**Comment by EricBoiseLGSVL** [comment]
This also may be a backend issue, see #1938 and #1937.  We are looking into it now, thanks for posting

**Comment by EricBoiseLGSVL** [comment]
Fixed, thanks for posting.  reopen the issue if you still have issues.  Seems a node crashed without a warning.

**Comment by JordanCrawfordx** [comment]
It works! :D Thanks for the fix.
