### ISSUE TITLE
Could not turn on the perception module.

### ISSUE THREAD

**Issue by lesun90** [lgsvl/simulator#21]
I followed the íntruction, everything work, except the perception module.

By the way, awesome simulator. Really impressive.
Thank you.

**Comment by hadiTab** [comment]
What issues did you have with Perception? Any specific errors?
You can try launching perception from a terminal (inside docker) instead of from dreamview to get some print statements. Use the following command:

`./scripts/perception.sh start_fe`

**Comment by lesun90** [comment]
My bad, I did not build the cuda for perception.

Thank you

**Comment by yangydavid** [comment]
@lesun90 Hi, I'm kind of having a similar issue, could you elaborate a bit more  about how you built the cuda for perception?

**Comment by martins-mozeiko** [comment]
You need to do those things only if you use original Apollo docker image. If you use docker image built by us, you don't need to install Nvidia driver or cuDNN inside docker. Its already there.

**Comment by lesun90** [comment]
> You need to do those things only if you use original Apollo docker image. If you use docker image built by us, you don't need to install Nvidia driver or cuDNN inside docker. Its already there.

Yes, exactly, we were using our own image. You guy should put a note in readme so people aware of this. I think anyone who tries your simulator already uses a docker image from apollo before.

**Comment by yangydavid** [comment]
@lesun90 @martins-mozeiko Hi, thanks for the comments, while the issue was still not resolved. I am just using the docker-image that you built, so there should be no problem regrading with Nvidia driver or cuDNN. However, the error message I got from `perception.ERROR` is the following: `Check failed: error == cudaSuccess (8 vs. 0)  invalid device function`. By the way, the driver I installed on the machine is 396 and cuda version is 9.2, which is different from the one set in your docker image. I am wondering if there's anything related to it?

**Comment by martins-mozeiko** [comment]
If you use our image then what you install on your host does not matter. As long as you have Nvidia driver & cuda installed, everything should work (versions do not matter). For original Apollo image versions matter, and what is in docker should match what is on your host.

What GPU are you using? Maybe it is not supported by Apollo?

**Comment by lesun90** [comment]
Maybe your machine has difference nvidia card so it use another version of nvidia, and it will need a difference cuda version

> NVIDIA graphics driver R375 or newer for CUDA 8
> NVIDIA graphics driver R384 or newer for CUDA 9
> NVIDIA graphics driver R390 or newer for CUDA 9.2

I suggest try the following steps:
Install the correct version of your nvida card.
```
sudo add-apt-repository ppa:graphics-drivers
sudo apt-get update
sudo apt-get install nvidia-384
```

Download cuDNN (select correct version for your driver): [](https://developer.nvidia.com/rdp/cudnn-download)
(You will want both the 'Runtime Library' and 'Developer Library')
Install cuDNN
```
sudo dpkg -i libcudnn7_7.1.4.18-1+cuda8.0_amd64.deb
sudo dpkg -i libcudnn7-dev_7.1.4.18-1+cuda8.0_amd64.deb
```
Build Apollo with the GPU option within docker
./apollo.sh build_gpu

In my case it works.

Good luck.

**Comment by yangydavid** [comment]
@martins-mozeiko  Hi Martins, yes I am using the nvidia-docker-image. It is still not working. I am wondering if there's anything to do with rosversion? Since I am using Ubuntu 16.04, the only ros I can install is `kinetic`, while the ros inside the docker is `indigo`. I am wondering if this is the cause?

**Comment by hadiTab** [comment]
@yangydavid what video card are you using? The version of ros installed on your machine will not affect anything. The docker image will use the indigo installed inside the container.

**Comment by MartinOrgiazzi** [comment]
Hi everyone ! I have also a Perception module launch issue and when I launch 
`$ ./scripts/perception.sh start_fe` in another console, I get this : 

`$ ./scripts/perception.sh start_fe
[cyber_launch_6413] INFO Stop cyber launch finished.
[cyber_launch_6413] INFO cyber_launch exit.
cyber_launch stop /apollo/modules/perception/production/launch/perception_all.launch
[cyber_launch_6421] INFO Stop cyber launch finished.
[cyber_launch_6421] INFO cyber_launch exit.
cyber_launch stop /apollo/modules/drivers/tools/image_decompress/launch/image_decompress.launch
[cyber_launch_6425] INFO Stop cyber launch finished.
[cyber_launch_6425] INFO cyber_launch exit.
cyber_launch stop /apollo/modules/transform/launch/static_transform.launch
cyber_launch start /apollo/modules/transform/launch/static_transform.launch &
cyber_launch start /apollo/modules/drivers/tools/image_decompress/launch/image_decompress.launch &
cyber_launch start /apollo/modules/perception/production/launch/perception_all.launch &
morgiazzi@in_dev_docker:/apollo$ [cyber_launch_6429] INFO Launch file [/apollo/modules/drivers/tools/image_decompress/launch/image_decompress.launch]
[cyber_launch_6429] INFO ========================================================================================================================
[cyber_launch_6430] INFO Launch file [/apollo/modules/perception/production/launch/perception_all.launch]
[cyber_launch_6430] INFO ========================================================================================================================
[cyber_launch_6429] INFO Load module [image_decompress] library: [mainboard_default_6429] [CYBER_DEFAULT] conf: [/apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag] exception_handler: []
[cyber_launch_6430] INFO Load module [perception] library: [perception] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception.dag] exception_handler: []
[cyber_launch_6429] INFO Start process [mainboard_default_6429] successfully. pid: 6432
[cyber_launch_6429] INFO ------------------------------------------------------------------------------------------------------------------------
[cyber_launch_6428] INFO Launch file [/apollo/modules/transform/launch/static_transform.launch]
[cyber_launch_6428] INFO ========================================================================================================================
[cyber_launch_6428] INFO Load module [static_transform] library: [mainboard_default_6428] [CYBER_DEFAULT] conf: [/apollo/modules/transform/dag/static_transform.dag] exception_handler: []
[cyber_launch_6430] INFO Start process [perception] successfully. pid: 6431
[cyber_launch_6430] INFO ------------------------------------------------------------------------------------------------------------------------
[cyber_launch_6430] INFO Load module [perception_camera] library: [perception] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag] exception_handler: []
[cyber_launch_6430] INFO Load module [perception_traffic_light] library: [perception_trafficlights] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag] exception_handler: []
[cyber_launch_6430] INFO Start process [perception_trafficlights] successfully. pid: 6436
[cyber_launch_6430] INFO ------------------------------------------------------------------------------------------------------------------------
[cyber_launch_6428] INFO Start process [mainboard_default_6428] successfully. pid: 6434
[cyber_launch_6428] INFO ------------------------------------------------------------------------------------------------------------------------
[perception: WARNING: Logging before InitGoogleLogging() is written to STDERR] perception: WARNING: Logging before InitGoogleLogging() is written to STDERR
[perception: I0531 16:35:54.378098  6431 module_argument.cc:85] [] command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception.dag /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag -p perception -s CYBER_DEFAULT ] perception: I0531 16:35:54.378098  6431 module_argument.cc:85] [] command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception.dag /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag -p perception -s CYBER_DEFAULT 
[perception: I0531 16:35:54.378859  6431 global_data.cc:150] [] host ip: 10.240.9.52] perception: I0531 16:35:54.378859  6431 global_data.cc:150] [] host ip: 10.240.9.52
[perception: I0531 16:35:54.379588  6431 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is perception, has 2 dag conf] perception: I0531 16:35:54.379588  6431 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is perception, has 2 dag conf
[perception: I0531 16:35:54.379598  6431 module_argument.cc:64] [] dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception.dag] perception: I0531 16:35:54.379598  6431 module_argument.cc:64] [] dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception.dag
[perception: I0531 16:35:54.379601  6431 module_argument.cc:64] [] dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag] perception: I0531 16:35:54.379601  6431 module_argument.cc:64] [] dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag
[mainboard_default_6429: WARNING: Logging before InitGoogleLogging() is written to STDERR] mainboard_default_6429: WARNING: Logging before InitGoogleLogging() is written to STDERR
[mainboard_default_6429: I0531 16:35:54.390566  6432 module_argument.cc:85] [] command: mainboard -d /apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag -p mainboard_default_6429 -s CYBER_DEFAULT ] mainboard_default_6429: I0531 16:35:54.390566  6432 module_argument.cc:85] [] command: mainboard -d /apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag -p mainboard_default_6429 -s CYBER_DEFAULT 
[mainboard_default_6429: I0531 16:35:54.391083  6432 global_data.cc:150] [] host ip: 10.240.9.52] mainboard_default_6429: I0531 16:35:54.391083  6432 global_data.cc:150] [] host ip: 10.240.9.52
[mainboard_default_6429: I0531 16:35:54.391752  6432 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is mainboard_default_6429, has 1 dag conf] mainboard_default_6429: I0531 16:35:54.391752  6432 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is mainboard_default_6429, has 1 dag conf
[mainboard_default_6429: I0531 16:35:54.391765  6432 module_argument.cc:64] [] dag_conf: /apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag] mainboard_default_6429: I0531 16:35:54.391765  6432 module_argument.cc:64] [] dag_conf: /apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag
[mainboard_default_6428: WARNING: Logging before InitGoogleLogging() is written to STDERR] mainboard_default_6428: WARNING: Logging before InitGoogleLogging() is written to STDERR
[mainboard_default_6428: I0531 16:35:54.419993  6434 module_argument.cc:85] [] command: mainboard -d /apollo/modules/transform/dag/static_transform.dag -p mainboard_default_6428 -s CYBER_DEFAULT ] mainboard_default_6428: I0531 16:35:54.419993  6434 module_argument.cc:85] [] command: mainboard -d /apollo/modules/transform/dag/static_transform.dag -p mainboard_default_6428 -s CYBER_DEFAULT 
[mainboard_default_6428: I0531 16:35:54.421075  6434 global_data.cc:150] [] host ip: 10.240.9.52] mainboard_default_6428: I0531 16:35:54.421075  6434 global_data.cc:150] [] host ip: 10.240.9.52
[mainboard_default_6428: I0531 16:35:54.421875  6434 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is mainboard_default_6428, has 1 dag conf] mainboard_default_6428: I0531 16:35:54.421875  6434 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is mainboard_default_6428, has 1 dag conf
[mainboard_default_6428: I0531 16:35:54.422260  6434 module_argument.cc:64] [] dag_conf: /apollo/modules/transform/dag/static_transform.dag] mainboard_default_6428: I0531 16:35:54.422260  6434 module_argument.cc:64] [] dag_conf: /apollo/modules/transform/dag/static_transform.dag
[perception_trafficlights: WARNING: Logging before InitGoogleLogging() is written to STDERR] perception_trafficlights: WARNING: Logging before InitGoogleLogging() is written to STDERR
[perception_trafficlights: I0531 16:35:54.425750  6436 module_argument.cc:85] [] command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag -p perception_trafficlights -s CYBER_DEFAULT ] perception_trafficlights: I0531 16:35:54.425750  6436 module_argument.cc:85] [] command: mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag -p perception_trafficlights -s CYBER_DEFAULT 
[perception_trafficlights: I0531 16:35:54.426244  6436 global_data.cc:150] [] host ip: 10.240.9.52] perception_trafficlights: I0531 16:35:54.426244  6436 global_data.cc:150] [] host ip: 10.240.9.52
[perception_trafficlights: I0531 16:35:54.426865  6436 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is perception_trafficlights, has 1 dag conf] perception_trafficlights: I0531 16:35:54.426865  6436 module_argument.cc:61] [] binary_name_ is mainboard, process_group_ is perception_trafficlights, has 1 dag conf
[perception_trafficlights: I0531 16:35:54.426877  6436 module_argument.cc:64] [] dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag] perception_trafficlights: I0531 16:35:54.426877  6436 module_argument.cc:64] [] dag_conf: /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag
[mainboard_default_6428: E0531 16:35:54.519428  6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_front_up_novatel_extrinsics.yaml] mainboard_default_6428: E0531 16:35:54.519428  6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_front_up_novatel_extrinsics.yaml
[mainboard_default_6428: E0531 16:35:54.519486  6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_front_novatel_extrinsics.yaml] mainboard_default_6428: E0531 16:35:54.519486  6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_front_novatel_extrinsics.yaml
[mainboard_default_6428: E0531 16:35:54.519510  6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_rear_left_novatel_extrinsics.yaml] mainboard_default_6428: E0531 16:35:54.519510  6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_rear_left_novatel_extrinsics.yaml
[mainboard_default_6428: E0531 16:35:54.519528  6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_rear_right_novatel_extrinsics.yaml] mainboard_default_6428: E0531 16:35:54.519528  6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/drivers/velodyne/params/lidar16_rear_right_novatel_extrinsics.yaml
[mainboard_default_6428: E0531 16:35:54.529289  6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/perception/data/params/radar_rear_extrinsics.yaml] mainboard_default_6428: E0531 16:35:54.529289  6434 static_transform_component.cc:57] [static_transform] Extrinsic yaml file is noe exists: /apollo/modules/perception/data/params/radar_rear_extrinsics.yaml
[mainboard_default_6429: E0531 16:35:54.853380  6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_front_6mm_decompress], please ensure that each node has a unique name.] mainboard_default_6429: E0531 16:35:54.853380  6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_front_6mm_decompress], please ensure that each node has a unique name.
[mainboard_default_6429: E0531 16:35:54.853554  6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_front_12mm_decompress], please ensure that each node has a unique name.] mainboard_default_6429: E0531 16:35:54.853554  6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_front_12mm_decompress], please ensure that each node has a unique name.
[mainboard_default_6429: E0531 16:35:54.853622  6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_left_fisheye_decompress], please ensure that each node has a unique name.] mainboard_default_6429: E0531 16:35:54.853622  6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_left_fisheye_decompress], please ensure that each node has a unique name.
[mainboard_default_6429: E0531 16:35:54.853683  6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_right_fisheye_decompress], please ensure that each node has a unique name.] mainboard_default_6429: E0531 16:35:54.853683  6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_right_fisheye_decompress], please ensure that each node has a unique name.
[mainboard_default_6429: E0531 16:35:54.853744  6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_rear_6mm_decompress], please ensure that each node has a unique name.] mainboard_default_6429: E0531 16:35:54.853744  6535 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[camera_rear_6mm_decompress], please ensure that each node has a unique name.
[mainboard_default_6428: E0531 16:35:54.891752  6527 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[static_transform], please ensure that each node has a unique name.] mainboard_default_6428: E0531 16:35:54.891752  6527 node_manager.cc:101] [mainboard] this process will be terminated due to duplicated node[static_transform], please ensure that each node has a unique name.
[mainboard_default_6429: ] mainboard_default_6429: 
[mainboard_default_6428: ] mainboard_default_6428: 
[cyber_launch_6429] ERROR Process [mainboard_default_6429] has finished. [pid 6432, cmd mainboard -d /apollo/modules/drivers/tools/image_decompress/dag/image_decompress.dag -p mainboard_default_6429 -s CYBER_DEFAULT].
[cyber_launch_6429] INFO All processes has died.
[cyber_launch_6429] INFO Cyber exit.
[cyber_launch_6429] INFO All processes have been stopped.
[cyber_launch_6428] ERROR Process [mainboard_default_6428] has finished. [pid 6434, cmd mainboard -d /apollo/modules/transform/dag/static_transform.dag -p mainboard_default_6428 -s CYBER_DEFAULT].
[cyber_launch_6428] INFO All processes has died.
[cyber_launch_6428] INFO Cyber exit.
[cyber_launch_6428] INFO All processes have been stopped.
[perception_trafficlights: [NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf'] perception_trafficlights: [NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf'
[perception_trafficlights: [NVBLAS] Cannot open default config file 'nvblas.conf'] perception_trafficlights: [NVBLAS] Cannot open default config file 'nvblas.conf'
[perception_trafficlights: [NVBLAS] Config parsed] perception_trafficlights: [NVBLAS] Config parsed
[perception_trafficlights: [NVBLAS] CPU Blas library need to be provided] perception_trafficlights: [NVBLAS] CPU Blas library need to be provided
[perception: [NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf'] perception: [NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf'
[perception: [NVBLAS] Cannot open default config file 'nvblas.conf'] perception: [NVBLAS] Cannot open default config file 'nvblas.conf'
[perception: [NVBLAS] Config parsed] perception: [NVBLAS] Config parsed
[perception: [NVBLAS] CPU Blas library need to be provided] perception: [NVBLAS] CPU Blas library need to be provided
[perception_trafficlights: F0531 16:36:00.200565  6495 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory] perception_trafficlights: F0531 16:36:00.200565  6495 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
[perception_trafficlights: *** Check failure stack trace: ***] perception_trafficlights: *** Check failure stack trace: ***
[perception_trafficlights:     @     0x7fb83b661ec0  google::LogMessage::Fail()] perception_trafficlights:     @     0x7fb83b661ec0  google::LogMessage::Fail()
[perception_trafficlights:     @     0x7fb83b661e07  google::LogMessage::SendToLog()] perception_trafficlights:     @     0x7fb83b661e07  google::LogMessage::SendToLog()
[perception_trafficlights:     @     0x7fb83b6617de  google::LogMessage::Flush()] perception_trafficlights:     @     0x7fb83b6617de  google::LogMessage::Flush()
[perception_trafficlights:     @     0x7fb83b66483b  google::LogMessageFatal::~LogMessageFatal()] perception_trafficlights:     @     0x7fb83b66483b  google::LogMessageFatal::~LogMessageFatal()
[perception_trafficlights:     @     0x7fb7c025cfa0  caffe::SyncedMemory::mutable_gpu_data()] perception_trafficlights:     @     0x7fb7c025cfa0  caffe::SyncedMemory::mutable_gpu_data()
[perception_trafficlights:     @     0x7fb7c011f1c2  caffe::Blob<>::mutable_gpu_data()] perception_trafficlights:     @     0x7fb7c011f1c2  caffe::Blob<>::mutable_gpu_data()
[perception_trafficlights:     @     0x7fb7c02ec176  caffe::EltwiseLayer<>::Forward_gpu()] perception_trafficlights:     @     0x7fb7c02ec176  caffe::EltwiseLayer<>::Forward_gpu()
[perception_trafficlights:     @     0x7fb7c026489c  caffe::Net<>::ForwardFromTo()] perception_trafficlights:     @     0x7fb7c026489c  caffe::Net<>::ForwardFromTo()
[perception_trafficlights:     @     0x7fb7c0264c95  caffe::Net<>::Forward()] perception_trafficlights:     @     0x7fb7c0264c95  caffe::Net<>::Forward()
[perception_trafficlights:     @     0x7fb7edb3ced1  apollo::perception::inference::CaffeNet::Infer()] perception_trafficlights:     @     0x7fb7edb3ced1  apollo::perception::inference::CaffeNet::Infer()
[perception_trafficlights:     @     0x7fb7eeb32ea5  apollo::perception::camera::TrafficLightDetection::Inference()] perception_trafficlights:     @     0x7fb7eeb32ea5  apollo::perception::camera::TrafficLightDetection::Inference()
[perception_trafficlights:     @     0x7fb7eeb3365f  apollo::perception::camera::TrafficLightDetection::Detect()] perception_trafficlights:     @     0x7fb7eeb3365f  apollo::perception::camera::TrafficLightDetection::Detect()
[perception_trafficlights:     @     0x7fb7eeffd800  apollo::perception::camera::TrafficLightCameraPerception::Perception()] perception_trafficlights:     @     0x7fb7eeffd800  apollo::perception::camera::TrafficLightCameraPerception::Perception()
[perception_trafficlights:     @     0x7fb826411add  apollo::perception::onboard::TrafficLightsPerceptionComponent::OnReceiveImage()] perception_trafficlights:     @     0x7fb826411add  apollo::perception::onboard::TrafficLightsPerceptionComponent::OnReceiveImage()
[perception_trafficlights:     @     0x7fb82642daa4  _ZNKSt7_Mem_fnIMN6apollo10perception7onboard32TrafficLightsPerceptionComponentEFvSt10shared_ptrINS0_7drivers5ImageEERKSsEEclIJRKS7_RSsEvEEvPS3_DpOT_] perception_trafficlights:     @     0x7fb82642daa4  _ZNKSt7_Mem_fnIMN6apollo10perception7onboard32TrafficLightsPerceptionComponentEFvSt10shared_ptrINS0_7drivers5ImageEERKSsEEclIJRKS7_RSsEvEEvPS3_DpOT_
[perception_trafficlights:     @     0x7fb82642a20e  _ZNSt5_BindIFSt7_Mem_fnIMN6apollo10perception7onboard32TrafficLightsPerceptionComponentEFvSt10shared_ptrINS1_7drivers5ImageEERKSsEEPS4_St12_PlaceholderILi1EESsEE6__callIvIRKS8_EILm0ELm1ELm2EEEET_OSt5tupleIIDpT0_EESt12_Index_tupleIIXspT1_EEE] perception_trafficlights:     @     0x7fb82642a20e  _ZNSt5_BindIFSt7_Mem_fnIMN6apollo10perception7onboard32TrafficLightsPerceptionComponentEFvSt10shared_ptrINS1_7drivers5ImageEERKSsEEPS4_St12_PlaceholderILi1EESsEE6__callIvIRKS8_EILm0ELm1ELm2EEEET_OSt5tupleIIDpT0_EESt12_Index_tupleIIXspT1_EEE
[perception_trafficlights:     @     0x7fb8264263e3  _ZNSt5_BindIFSt7_Mem_fnIMN6apollo10perception7onboard32TrafficLightsPerceptionComponentEFvSt10shared_ptrINS1_7drivers5ImageEERKSsEEPS4_St12_PlaceholderILi1EESsEEclIJRKS8_EvEET0_DpOT_] perception_trafficlights:     @     0x7fb8264263e3  _ZNSt5_BindIFSt7_Mem_fnIMN6apollo10perception7onboard32TrafficLightsPerceptionComponentEFvSt10shared_ptrINS1_7drivers5ImageEERKSsEEPS4_St12_PlaceholderILi1EESsEEclIJRKS8_EvEET0_DpOT_
[perception_trafficlights:     @     0x7fb826422a99  std::_Function_handler<>::_M_invoke()] perception_trafficlights:     @     0x7fb826422a99  std::_Function_handler<>::_M_invoke()
[perception_trafficlights:     @     0x7fb8262fbf13  std::function<>::operator()()] perception_trafficlights:     @     0x7fb8262fbf13  std::function<>::operator()()
[perception_trafficlights:     @     0x7fb8262f306f  _ZZN6apollo5cyber6ReaderINS_7drivers5ImageEE4InitEvENKUlRKSt10shared_ptrIS3_EE_clES8_] perception_trafficlights:     @     0x7fb8262f306f  _ZZN6apollo5cyber6ReaderINS_7drivers5ImageEE4InitEvENKUlRKSt10shared_ptrIS3_EE_clES8_
[perception_trafficlights:     @     0x7fb82630a8a5  _ZNSt17_Function_handlerIFvRKSt10shared_ptrIN6apollo7drivers5ImageEEEZNS1_5cyber6ReaderIS3_E4InitEvEUlS6_E_E9_M_invokeERKSt9_Any_dataS6_] perception_trafficlights:     @     0x7fb82630a8a5  _ZNSt17_Function_handlerIFvRKSt10shared_ptrIN6apollo7drivers5ImageEEEZNS1_5cyber6ReaderIS3_E4InitEvEUlS6_E_E9_M_invokeERKSt9_Any_dataS6_
[perception_trafficlights:     @     0x7fb8262fbf13  std::function<>::operator()()] perception_trafficlights:     @     0x7fb8262fbf13  std::function<>::operator()()
[perception_trafficlights:     @     0x7fb8262fc1d2  _ZZZN6apollo5cyber8croutine20CreateRoutineFactoryINS_7drivers5ImageESt8functionIFvRKSt10shared_ptrIS4_EEEEENS1_14RoutineFactoryEOT0_RKS6_INS0_4data11DataVisitorIT_NS0_8NullTypeESI_SI_EEEENKUlvE_clEvENKUlvE_clEv] perception_trafficlights:     @     0x7fb8262fc1d2  _ZZZN6apollo5cyber8croutine20CreateRoutineFactoryINS_7drivers5ImageESt8functionIFvRKSt10shared_ptrIS4_EEEEENS1_14RoutineFactoryEOT0_RKS6_INS0_4data11DataVisitorIT_NS0_8NullTypeESI_SI_EEEENKUlvE_clEvENKUlvE_clEv
[perception_trafficlights:     @     0x7fb82631b132  _ZNSt17_Function_handlerIFvvEZZN6apollo5cyber8croutine20CreateRoutineFactoryINS1_7drivers5ImageESt8functionIFvRKSt10shared_ptrIS6_EEEEENS3_14RoutineFactoryEOT0_RKS8_INS2_4data11DataVisitorIT_NS2_8NullTypeESK_SK_EEEENKUlvE_clEvEUlvE_E9_M_invokeERKSt9_Any_data] perception_trafficlights:     @     0x7fb82631b132  _ZNSt17_Function_handlerIFvvEZZN6apollo5cyber8croutine20CreateRoutineFactoryINS1_7drivers5ImageESt8functionIFvRKSt10shared_ptrIS6_EEEEENS3_14RoutineFactoryEOT0_RKS8_INS2_4data11DataVisitorIT_NS2_8NullTypeESK_SK_EEEENKUlvE_clEvEUlvE_E9_M_invokeERKSt9_Any_data
[perception_trafficlights:     @     0x7fb8485456e8  std::function<>::operator()()] perception_trafficlights:     @     0x7fb8485456e8  std::function<>::operator()()
[perception_trafficlights:     @     0x7fb840091cbc  apollo::cyber::croutine::CRoutine::Run()] perception_trafficlights:     @     0x7fb840091cbc  apollo::cyber::croutine::CRoutine::Run()
[perception_trafficlights:     @     0x7fb840090f55  apollo::cyber::croutine::(anonymous namespace)::CRoutineEntry()] perception_trafficlights:     @     0x7fb840090f55  apollo::cyber::croutine::(anonymous namespace)::CRoutineEntry()
[cyber_launch_6430] ERROR Process [perception] has finished. [pid 6431, cmd mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception.dag /apollo/modules/perception/production/dag/dag_streaming_perception_camera.dag -p perception -s CYBER_DEFAULT].
[cyber_launch_6430] ERROR Process [perception_trafficlights] has finished. [pid 6436, cmd mainboard -d /apollo/modules/perception/production/dag/dag_streaming_perception_trafficlights.dag -p perception_trafficlights -s CYBER_DEFAULT].
[cyber_launch_6430] INFO All processes has died.
[cyber_launch_6430] INFO Cyber exit.
[cyber_launch_6430] INFO All processes have been stopped.
`

Have you a idea of what I can do ?
Thanks

**Comment by martins-mozeiko** [comment]
```
Check failed: error == cudaSuccess (2 vs. 0) out of memory
```

This seems to be the real error message. It seems GPU is running out of memory? What kind of GPU are you using?

**Comment by MartinOrgiazzi** [comment]
I use a NVIDIA  Quadro M2200 .

**Comment by MartinOrgiazzi** [comment]
As the CUDA versions on the docker and the local were different I downgraded the local one to have 8.0 on both. But still it doesn't work. Also mu distribution is Fedora 29, it could be important to notice that, couldn't it ?

**Comment by martins-mozeiko** [comment]
Cuda SDK versions in docker and on host does not matter. Apollo docker image only requires your host Nvidia driver (not SDK) to support cuda, and as image is using nvidia-runtime - it will use exactly same version inside docker image.

I think your issue may be that your GPU is not supported. Officially Apollo supports only GTX 1080 (although it runs with 1070/1060 and similar hardware).  According to this table: https://en.wikipedia.org/wiki/CUDA#GPUs_supported the 1080 is Pascal architecture with with 6.1 compute capability. M2200 seems to be Maxwell architecture with 5.2 compute capability. You need to make sure Apollo perception code is compiled with 5.2 support. I suggest clarifying this with Apollo developers.

**Comment by MartinOrgiazzi** [comment]
All right I will ask, thank you for the advices. But I think it is a bit strange a could run Apollo with the rosbag of data they attached and not in live with the simulator isn't it ?

**Comment by martins-mozeiko** [comment]
Are you running simulator in same laptop as Apollo? If Apollo works without simulator then the issue probably is not enough memory as cuda is already saying. Both Simulator and Apollo wants to use GPU at the same time.

**Comment by leFeuilluZer** [comment]
Yes I am. 
I guess I have no choice but moving on other GPU if I want to run everything well then...

Thanks for the help @martins-mozeiko

**Comment by leFeuilluZer** [comment]
However, even if I launch only one component in the perception module, I don't have a GPU out of memory error message but it still crashes  : 
![image](https://user-images.githubusercontent.com/48589344/58956846-acca4e00-879f-11e9-8ba3-aafe4e02c447.png)

**Comment by martins-mozeiko** [comment]
I can suggest running perception process under gdb, and when it crashes check the callstack with `bt` command. Maybe that will give hint what is crashing here.

**Comment by leFeuilluZer** [comment]
![image](https://user-images.githubusercontent.com/48589344/59018135-7a732c00-8845-11e9-8f56-28d7004914cb.png)
