### ISSUE TITLE
Error when using Radar on Rigged_lgsvl

### ISSUE THREAD

**Issue by alexsimon1** [lgsvl/simulator#227]
hello,

i get the following error Message when i activate the Radar sensor on the rigged_lgsvl ego vehicle.
[ERROR] [1562152707.426288]: [Client 1] publish: Cannot infer topic type for topic /apollo/sensor/conti_radar as it is not yet advertised

**Comment by daviduhm** [comment]
This issue is because the XE_Rigged-lgsvl vehicle has a radar sensor with incorrect target environment, *Apollo*. At the moment, our radar sensor implementation only supports Apollo, which means it creates a ros/cyber message in apollo specific topic type `apollo.drivers.ContiRadarObs` and publishes to rosbridge. You are getting the error message because most probably you are not running Apollo with XE_Rigged-lgsvl vehicle and thus your rosbridge doesn't know about this message type.

I guess we should better remove a radar sensor from XE_Rigged-lgsvl vehicle as it doesn't support target environments other than Apollo. Supporting radar sensor for environments other than Apollo is in our plan, but that will come later. Alternatively, you can write your own message type definitions and code to publish it. Please take a look at [RadarSensor.cs](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/RadarSensor.cs) and [PbMsgs.cs](https://github.com/lgsvl/simulator/blob/91d60e9232ebfc2b3fc013265af8ef02c1d907b0/Assets/Scripts/Ros/PbMsgs.cs#L788). You can see there how we define message definitions for radar and how to create a message and publish it to rosbridge.
