### ISSUE TITLE
How Can I get the radar's data from lgsvl-sim by python script

### ISSUE THREAD

**Issue by JIXIMD** [lgsvl/simulator#273]

**Comment by daohu527** [comment]
Currently there is no python Api to save radar information, but there is a lidar and camera information.
I don't know if the new version is added.

**Comment by JIXIMD** [comment]
Is there any other way to get radar measurements?

**Comment by martins-mozeiko** [comment]
Because our radar simulation is done on high level (output is ROS/Cyber message) there is no low level data to get. If all you need is nearby cars in range of radar, you can collect them yourself by querying position of each npc and checking if their position/rotations/velocity meets your criteria about being detected.

**Comment by JIXIMD** [comment]
Thank you for @daohu527 @martins-mozeiko replys. right, I want to get the relative distance and speed between NPC vehicles and EGOvehicles.My model is shown in the picture below
![image](https://user-images.githubusercontent.com/38455693/62912162-889b7680-bdb9-11e9-93e8-55d251bf0ee4.png)
my python code:
     dis_x = ego.state.transform.position.x - npc.state.transform.position.x
     v_x	= ego.state.velocity.x - npc.state.velocity.x
But I get the error message :
  v_x	= ego.state.velocity.x - npc.state.velocity.x
                                                                         ^
  IndentationError: unindent does not match any outer indentation level

Then,How do I get the npc car's velocity?
