### ISSUE TITLE
No predefined maps or vehicles in browser side and Web UI build error on Win7 

### ISSUE THREAD

**Issue by kissofwind** [lgsvl/simulator#327]
Today when I try to build the latest  2019.07 Release, I found two issues. 
!. After building lg simulator, I can find no predefined maps or vehicles in my browser side, while on my colleagues's computer there are default vehicles and maps. The source code and the operations are the same.   
2. When I try to build lg simulator on win7 the web ui build is always failure, but when I try to build it on my win10 laptop it can succeed. So I want to know is there any way that I can build it on win7. currently i do not want to change my os.

**Comment by martins-mozeiko** [comment]
Predefined maps and vehicles are added to your simulator only when you run binary build we provide. Because only binary knows exact version of maps/vehicles to download. Different releases of simulator will have different versions of maps/vehicles added. When you run simulator in Unity Editor we cannot guarantee compatibility of map/vehicle asset bundles, so it is up to you to add them manually in web interface. You can get asset bundles for 2019.07 release here: https://content.lgsvlsimulator.com

If you want to automatically add maps/vehicles to your simulator, delete the current database (in `~/.config/unity3d/LG Silicon Valley Lab/LGSVL Simulator/data.db` location). Then launch binary. It will populate database with default asset bundles and start the download.

What error do you get when building WebUI? Check that you have installed all the dependencies by running `npm install` in WebUI folder. If that does not help, run `npm run pack` in same folder to see any error messages.
