### ISSUE TITLE
Failed to load module "Canberra-gtk-module"

### ISSUE THREAD

**Issue by Francisobiagwu** [lgsvl/simulator#328]
Each time I try to open the BorregasAve, no bridge, data collection. I get this error. 
Failed to load module "canberra-gtk-module"
Aborted (core dumped)

![test](https://user-images.githubusercontent.com/19335305/64025279-53598d00-cb0a-11e9-821c-e46f7723b9ed.png)

**Comment by martins-mozeiko** [comment]
This error message about canberra is harmless, it comes from some internal Unity dependencies which we do not use.

To understand what crashes here, check the log file at `~/.config/unity3d/Editor/Player.log` - there should be some error messages at the bottom.

One potential reason is that you do not have vulkan client libraries installed. Unity HDRP rendering on linux uses Vulkan instead of OpenGL. Check if you have `libvulkan1` package installed.

**Comment by zhouchengming1** [comment]
Try this: sudo apt install libcanberra-gtk-module libcanberra-gtk3-module

**Comment by martins-mozeiko** [comment]
@zhouchengming1  libcanberra is completely irrelevant here. It is some optional GTK dependency that we do not use. GTK libraries probably try to load it this module it exists. But everything still works if it does not exist.

**Comment by ntutangyun** [comment]
> This error message about canberra is harmless, it comes from some internal Unity dependencies which we do not use.
> 
> To understand what crashes here, check the log file at `~/.config/unity3d/Editor/Player.log` - there should be some error messages at the bottom.
> 
> One potential reason is that you do not have vulkan client libraries installed. Unity HDRP rendering on linux uses Vulkan instead of OpenGL. Check if you have `libvulkan1` package installed.

this actually solved the issue.

**Comment by ashish-roopan** [comment]
@martins-mozeiko . I am getting the same error when running pose detection on GPU. The ```libvulkan1``` package is installed and can't find any path ```~/.config/unity3d/Editor/Player.log``` for checking the log file. Can you assist me on what to do ?
