### ISSUE TITLE
car speed

### ISSUE THREAD

**Issue by yangjiongfeng** [lgsvl/simulator#355]
I can control the car through “/vehicle_cmd”.
I want to know the speed of the car in real time.
But no

![选区_094](https://user-images.githubusercontent.com/27730697/64664529-08346800-d482-11e9-842b-05caf8b054e5.png)

**Comment by martins-mozeiko** [comment]
I'm confused - is this Autoware or Apollo? Because topic list includes both names.

For Apollo you can get speed from `/apollo/canbus/chassis` topic - [speed_mps](https://github.com/ApolloAuto/apollo/blob/master/modules/canbus/proto/chassis.proto#L61) field or `/apollo/sensor/gnss/best_pose` topic - [localization.linear_velocity](https://github.com/ApolloAuto/apollo/blob/master/modules/localization/proto/pose.proto#L35) field.

For Autoware you can get it from `/odom` topic -  twist.twist.linear field in [nav_msgs/Odometry](http://docs.ros.org/melodic/api/nav_msgs/html/msg/Odometry.html) message type.
