### ISSUE TITLE
Launching Autoware alongside LGSVL Simulator

### ISSUE THREAD

**Issue by obi5656** [lgsvl/simulator#373]
Self-position estimation is not performed.
I want to execute like this sample image.
![autoware-ndt-matching](https://user-images.githubusercontent.com/55091660/65120792-27566b00-da29-11e9-9851-8496f51ede58.png)

In the 'Quick Start' tab, the time is not displayed on the right side of "Ref" of "Localization" like the image.
Is there a solution?
![Screenshot from 2019-09-18 15-30-34](https://user-images.githubusercontent.com/55091660/65122277-83ba8a00-da2b-11e9-9360-e5cbefea82c9.png)

Is there anything else to set other than the 'Quick Start' tab?

Please help me.

**Comment by obi56** [comment]
The reason why self-location estimation cannot be executed is that ROSBAG data is not clicked on "Play" in the "Simulation" tab?

Where is ROSBAG data distributed for autoware simulation on lgsvl simulator?

**Comment by hadiTab** [comment]
@obi56 there is no need for a rosbag. Rosbags are used for replaying previously collected data (which is what the autoware quickstart is using). Since the simulator provides a live stream of data, no rosbag is used.

There could be several reasons to why the localization is not working. We will need more information to figure out why. Here are several things you can do:

- After launching localization, look at the terminal that Autoware was launched from and see if there are any error messages. If so please share them with us.

- Make sure that you have downloaded the maps properly. We use git-lfs to store the pointcloud map in the autoware-data repository. If you do not have git-lfs installed the map will not be downloaded properly. A simple check will be to check the size of the PCD file for the map located in: `~/shared_dir/autoware-data/BorregasAve/data/map/pointcloud_map/BorregasAve.pcd`
If it is incredibly small (less than 1KB) that would mean that the file has not been downloaded and you should install git-lfs and download it.

**Comment by obi56** [comment]
When "Map" tab is pressed, "OK" is displayed, but this error appears.
![Screenshot from 2019-09-20 13-37-59](https://user-images.githubusercontent.com/55091660/65299919-74167f00-dbac-11e9-9a98-cdea5d942471.png)

Pressing "Localization" tab does not output an error.
![Screenshot from 2019-09-20 13-44-55](https://user-images.githubusercontent.com/55091660/65300049-0cacff00-dbad-11e9-9c7f-4334648d53b8.png)

I think the download using git-lfs has been successful.
![Screenshot from 2019-09-20 12-29-40](https://user-images.githubusercontent.com/55091660/65300146-72998680-dbad-11e9-8e07-6f1dcbc67007.png)

**Comment by hadiTab** [comment]
@obi56 seems like the map is there. I suspect that the localization is actually searching for a solution. It usually takes a while. Those numbers appear after it finds a pose. To help it out you can open up rviz and set an initial pose on the map near where the vehicle is located (by default this would be at the bottom of the map you see in rviz).

**Comment by obi56** [comment]
Even if you run '2D Pose Estimate' many times, the time is not displayed in the 'Localization' tab.

Is this an error related?
![Screenshot from 2019-09-30 12-10-22](https://user-images.githubusercontent.com/55091660/65847149-518a2000-e37b-11e9-9b6f-9ca604a8ef4f.png)

**Comment by hadiTab** [comment]
Can you run `rosnode info /ndt_matching` and paste the results here?

**Comment by obi5656** [comment]
Thank you.

![Screenshot from 2019-10-07 15-40-28](https://user-images.githubusercontent.com/55091660/66289959-f9be5c80-e918-11e9-9c06-314accc3cfa1.png)

**Comment by hadiTab** [comment]
I don't see anything that seems out of place. Unfortunately, I don't really have a solution for you.
In general, the ndt_matching localization is a bit finicky and it's usually the hardest part to get going correctly. I usually wait for a few minutes after enabling localization, and then set the 2D pose and it almost always works. If it doesn't I'll restart everything and try again. It's a bit painful, but allowing it to sit for a few minutes seems to somehow help it with searching for a correct pose. The folks at Autoware may have a better solution for this.

If you don't really care about using lidar-based localization and just want some form of localization working, another option is to use the GPS sensor. This is also not straight forward because of an issue with the GPS implementation in Autoware that makes it only work with Japanese coordinates. There is a fix for this (these three pull requests: [1](https://gitlab.com/autowarefoundation/autoware.ai/core_perception/merge_requests/26), [2](https://gitlab.com/autowarefoundation/autoware.ai/common/merge_requests/20), [3](https://gitlab.com/autowarefoundation/autoware.ai/utilities/merge_requests/27)). You'll need to apply these changes to the autoware source code and either run autoware from source or rebuild a docker image with the modified source code to run with the simulator. Once this is done you can use the `gnss_localizer` node and set it to plane 0 and it should provide good position estimates. It is a bit of extra work.

**Comment by obi5656** [comment]
Thank you.
I'll give it a try.
