### ISSUE TITLE
Where can I download San Francisco map for current version of the simulator?

### ISSUE THREAD

**Issue by cclinus** [lgsvl/simulator#400]
Where can I download San Francisco map for the current version of the simulator (2019.09)? It was there in previous versions but not the 2019.09.

Thanks.

**Comment by hadiTab** [comment]
The old San Francisco scene will not work in the new version of the simulator because we are using Unity's HDRP pipeline which requires changing the materials for all assets to support high detail rendering. It would be a significant effort and at the moment we do not have any plans to do it ourselves. We will be providing other high quality scenes soon though.

If you do wish to make the effort to convert the old San Francisco map over to the new simulator, the process is explained in https://github.com/lgsvl/simulator/issues/298#issuecomment-524074748.
