### ISSUE TITLE
Apollo 5.0 with LGSVL simulator error

### ISSUE THREAD

**Issue by bongjoonhyun** [lgsvl/simulator#417]
#417 # System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Ubuntu 18.04
- **Apollo installed from (source or binary)**: source with GPU enabled
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**: 5.0

### Steps to reproduce the issue:
I'm trying to run Apollo 5.0 with LGSVL simulator.

I've followed all the necessary instructions provided by both Apollo and LGSVL.

I confirmed that the connection between Apollo and LGSVL is successful; messages are going back and forth between the two.

But when I hit to go autonomous driving mode, the ego vehicle is driving weirdly and stuck after a few seconds.

I'm suspicious this might be because of the IMU sensor errors showing at the consol.

![Screenshot 2019-10-07 17 23 09](https://user-images.githubusercontent.com/46742698/66296890-8113cc00-e929-11e9-912b-6955e216c6fb.png)

Any ideas why this is happening and how to fix this?

**Comment by martins-mozeiko** [comment]
This kind of swerving happens because simulation is running too slow (which could be due to slow CPU or slow GPU). If simulation runs slow, then Apollo is receiving localization data too late. It will try to adjust movement, but that will happen way too late.

You should check that you can run Simulator with at least 30 frames/second. Going lower than 20 will make Apollo driving unstable.
