### ISSUE TITLE
advertise: Unable to load the manifest for package pb_msgs. Caused by: pb_msgs

### ISSUE THREAD

**Issue by JIXIMD** [lgsvl/simulator#425]
Hi, LG Team
  I want to use the canbus sensor without apollo,I wanted to use canbus sensors without Apollo, but failed without pb_msgs. How do I get pb_msgs?
![image](https://user-images.githubusercontent.com/38455693/66563308-1adcb280-eb90-11e9-8889-ecc69e972234.png)

Thank you

**Comment by Aquarian-source** [comment]
hey, i do not understand what you meant from "install rosbridge from upstream"
my case: i am running autoware specific message types for all other sensors, and want to make pb_msgs compatible for our rosbridge.

**Comment by martins-mozeiko** [comment]
rosbridge is standard ROS package: http://wiki.ros.org/rosbridge_suite

But it won't work with pb_msgs. If you need pb_msgs then you need to either take patches from our fork of it, or just simply use our fork. 

If you are just running Autoware, you don't need pb_msgs at all. That's why I suggested using rosbridge from upstream, not from our fork. But if you need to subscribe to Apollo specific pb_msgs messages, you'll need two things: 1) rosbridge with pb_msgs support, 2) actual pb_msgs message definitions (found in Apollo repository).

**Comment by Aquarian-source** [comment]
hey thankx for clarifying. 
in my case i have connected ROS with lg simulator using Autoware message types. i want to access Canbus sensor data. how can i do that? specially for velocity information

**Comment by martins-mozeiko** [comment]
If you are ok with just velocity on forward axis, then odometry sensor should give this information.

But if you need full 3d vector for velocity, then you would need to modify simulator code to publish this extra information. Currently nobody is publishing this, because Autoware did not need this information.
