### ISSUE TITLE
Adding external sensors not mounted to ego vehicle

### ISSUE THREAD

**Issue by fgrzeszc** [lgsvl/simulator#438]
Hi,

First, thanks for great work and releasing this wonderful product to the community.

Could you please tell me if it would be possible to add sensors that are not mounted to the ego vehicle? Specifically I would like to simulate view from multiple surveillance cameras observing the ego vehicle.

Really appreciate your time,
Filip

**Comment by martins-mozeiko** [comment]
There is no support right now for such functionality.

Technically sensors will work without the EGO vehicle (capturing data from environment). So they could be placed anywhere on map. But the problem is how to get data out of simulator. Currently sensors have assumption that there will be ROSBridge or CyberBridge connection provided by EGO vehicle.

So having senors send data without EGO vehicle will require some modifications to simulator code.

**Comment by Roman-jj** [comment]
As a workaround, I guess you could add a second stationary EGO vehicle somewhere on the side of the map and attach the sensors to it

**Comment by KrzysztofDabek** [comment]
> As a workaround, I guess you could add a second stationary EGO vehicle somewhere on the side of the map and attach the sensors to it

My idea would be to create an empty object with tag "Player" and no components like rigidbody collider or renderer. Adding sensors to it and letting the simulator add ROSBridge agent component.
My question. Would this work or do I need to make any changes in the code? 

For example here:
https://github.com/lgsvl/simulator/blob/dbf1704fc1def2d486500022ff38a6c2feca9fde/Assets/Scripts/Managers/AgentManager.cs#L168

**Comment by EricBoiseLGSVL** [comment]
@KrzysztofDabek We are releasing a feature soon called controllables.  This can be spawned in scene and can communicate with Agent custom sensor that then communicates with bridge.
