### ISSUE TITLE
how apollo and autoware is supported in 201909 release?

### ISSUE THREAD

**Issue by Vincent-Tsui-GWM** [lgsvl/simulator#451]
in 201904 release there is a ROSTargetEnvironment enum for the scripts to use to treat apollo platform and autoware platform differently .
but in 201909 release, there is no such enum, for example in CanbusSensor.cs there is one and only one 
```
Writer.Write(msg, null);
```
so I want to know what is the mechanism that only one write function can support different platforms.
thanks.

**Comment by martins-mozeiko** [comment]
We have abstracted sensor implementation from actual protocol (ROS1, ROS2, CyberRT).

Here is basic data flow how sensor information is published:

1) Sensor prepares data it wants to publish. Data is one classes in `Simulator.Bridge.Data` namespace. For example, for [ColorCamera sensor](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Sensors/ColorCameraSensor.cs) this is [Simulator.Bridge.Data.ImageData](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Bridge/Data/ImageData.cs) class. These classes are ROS/Cyber independent, they only contain information from sensor.

2) There are multiple bridges with different implementations. For example - RosBridge v1, RosBridge v2, CyberBridge. These bridges know how to convert generic Data class to ROS or Cyber specific message and publish over network. For most messages conversion happens by calling `Conversions.ConvertFrom` function. For example, the ImgeData is converted [here](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Bridge/Ros/RosConversions.cs#L20). This is place where actual ROS message is created.

3) Each message writer is implemented in different bridge - [RosWriter](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Bridge/Ros/RosWriter.cs), [CyberWriter](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Bridge/Cyber/CyberWriter.cs). But they share same interface - [IWriter](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Bridge/IWriter.cs). That's why sensor can write to any bridge implementation.
