### ISSUE TITLE
fail to launch simulator

### ISSUE THREAD

**Issue by simon13579** [lgsvl/simulator#477]
Hello,

I am using Ubuntu 16.04 in VMware, and I build the simulator from source code following the instructions, in the Unity output window some error shows:
![unity](https://user-images.githubusercontent.com/38149116/68541641-e5202900-03dc-11ea-9742-bb139fb7796e.png)

However Simulator.exe is still generated. I double click the .exe, the Simulator Configuration dialog shows and I click OK, then nothing happen, the simulator didn't show in browser.
![configuration](https://user-images.githubusercontent.com/38149116/68541693-d423e780-03dd-11ea-9afb-193d8253e945.png)

I also try to use the released executable from GitHub repository, but the problem is same. Is there anything more I can try?

Thanks.

**Comment by martins-mozeiko** [comment]
The error from Editor looks like it run out of memory when building code. Do you have allocated enough memory for your VM?

As for running binary, you should check logfile at `~/.config/unity3d/Unity/Editor/Editor.log` location. It should have more detailed information.

My guess would be that it cannot properly use GPU because of VM or drivers. Check that you have configured your VM correctly. Run any vulkan application to see if can show something. For example, `vulkaninfo` (on Ubuntu it is inside `vulkan-utils` package). Verify that it outputs something like this with information about your GPU:

```
GPU0:
VkPhysicalDeviceProperties:
---------------------------
	apiVersion     = 4198509 (1.1.109)
	driverVersion  = 1824866304 (0x6cc54000)
	vendorID       = 0x10de
	deviceID       = 0x1b80
	deviceType     = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
	deviceName     = GeForce GTX 1080
```

**Comment by simon13579** [comment]
Hello Martins，

Thanks, I think yes, it's because of VM. After I search the web according to your guess, I find out currently VM don't support vulkan. I will try on a real Ubuntu system, thanks.

Thanks.
