### ISSUE TITLE
Radar scan/spin speed

### ISSUE THREAD

**Issue by arslansarp** [lgsvl/simulator#489]
Hello Dear Community,

I added radar support to lgsvl but I would like to know the place  in code where the radar scan speed is included. I tried to look up the code inside in simulator. I couldn't manage to see it. 

I need your help urgently.

**Comment by martins-mozeiko** [comment]
Our radar is not spinning or scanning anything. It is simulated on high level - only data that is sent as ROS or Cyber messages are collected. Because simulator knows actual position of obstacles / other cars, it can directly use this information to prepare information with positions, velocities, etc..
