### ISSUE TITLE
Dreawview error

### ISSUE THREAD

**Issue by Francisobiagwu** [lgsvl/simulator#491]
I am currently following the instruction on using the apollo-5.0. I selected. But, the apollo kept showing the components as FATAL and ERROR. Also, the Routing editing is grayed out

![cyberRT](https://user-images.githubusercontent.com/19335305/68782998-44ae4c80-0608-11ea-94b9-40d1ffb1c985.png)
![local_machine](https://user-images.githubusercontent.com/19335305/68783006-4aa42d80-0608-11ea-9d82-9696a76de372.png)
![map_vehicles_ip_string](https://user-images.githubusercontent.com/19335305/68783011-4d068780-0608-11ea-971f-64c0998e1933.png)

![dreamview_error](https://user-images.githubusercontent.com/19335305/68782741-db2e3e00-0607-11ea-987f-f686c364def4.png)

**Comment by Francisobiagwu** [comment]
All the sensors are turned on. But the error persists. 
![sensors_turned_on](https://user-images.githubusercontent.com/19335305/68783838-a15e3700-0609-11ea-849b-3a001da7b137.png)

**Comment by martins-mozeiko** [comment]
It is OK to see FATAL/ERROR messages in Components panel. Those are status for hardware sensors which Apollo uses. But Simulator simulates sensors on ROS/Cyber level, so Apollo thinks hardware is not working. You can safely ignore those.

The problem why localization is not working is that you are using Autoware sensors. You probably took car which was preconfigured for Autoware sensors. Switching just the bridge type is not enough, because Autoware and Apollo topics are different. You can get full list of sensors Apollo needs here: https://www.lgsvlsimulator.com/docs/apollo5-0-json-example/#complete-json-configuration

And you don't need to "turn on" sensors. If they are added to vehicle in Json configuration, they will be working always. Clicking "eye" icon in Visualize panel inside Simulator only visualizes them for you on the screen.

**Comment by Francisobiagwu** [comment]
Thanks. That worked.
