### ISSUE TITLE
Gps Ground truth output

### ISSUE THREAD

**Issue by arslansarp** [lgsvl/simulator#514]
Hi,
I just want to fuse gps and imu for localization. However, ground truth coming from gps isn't looking relevant. Although , we collected same amount of message from topics, it shows weird plot. 
We have two truth models one of them is our model created by using ground_truth and the other one is the **raw** ground truth. The last one is the noisy version of our truth_model. 

I added some ss down here.

![k1](https://user-images.githubusercontent.com/33527769/69314344-f40ca400-0c44-11ea-815f-7b559a5e4079.png)

![k2](https://user-images.githubusercontent.com/33527769/69314350-f838c180-0c44-11ea-93f4-95ca7f36f497.png)

We are curious about  why this is happening.

**Comment by martins-mozeiko** [comment]
Hi.

Do I understand correctly, that green line are GPS coordinates from our sensor, but red line is actual location? And your concern is that they are so different?

What are units on axes? Are those meters? Because 10^-4 does not seem like a lot.

We know that there are some precision issues with our GPS conversion code. See #248 issue. We will be looking into that at some point. Maybe you are seeing same issue?
