### ISSUE TITLE
Can AssetBundle building include sensor configs in JSON format?

### ISSUE THREAD

**Issue by mehmetdogru** [lgsvl/simulator#525]
Hi everyone.

I am using LGSVL v2019.10 and i want to build assetbundles with sensor configurations(in JSON format). When i import the vehicle assetbundle in WebUI, JSON messages for that vehicle which include sensor configs should be imported as well. Is there a way to do it?

Thanks in advance.

**Comment by martins-mozeiko** [comment]
With current implementation you cannot do that.

In current design we want sensors be separated from vehicle assets because of multiple reasons:

1) same vehicle assets can be used in different configurations - full set of sensors to drive AD stack, just camera/lidar to collect data from perception, only gps for localization if perception is not needed (to improve performance), etc...

2) we want to distribute vehicles as binary bundles, not source assets. That means we cannot choose set of sensors - this choice must be done by users of bundle, not the creator.

That said, if you really need default set of sensors inside vehicle bundle, it should not be difficult to modify the code. You can include arbitrary files inside bundle (as it is zip file), so it should be possible to include extra json file that is read when vehicle is loaded, and if not sensors are specified in webui, read them from json file (if it is present). We would be ok to accept such change in pull request.
