### ISSUE TITLE
opendrive import error 

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#537]
failed in windows version of lgsvl
![image](https://user-images.githubusercontent.com/39210837/70048691-e02e4e00-1605-11ea-8509-acae607a4c1a.png)
I choosed the map below from opendrive official website：
![image](https://user-images.githubusercontent.com/39210837/70048721-f20ff100-1605-11ea-9912-d0ac56fba694.png)
The map is the same！
but succeed in linux version of lgsvl...
![Screenshot from 2019-12-03 20-49-30](https://user-images.githubusercontent.com/39210837/70052527-6d75a080-160e-11ea-82b8-32647d1ab379.png)

**Comment by martins-mozeiko** [comment]
Are you sure you are selecting same file when importing it on Linux?

I have tried it, and it fails with same error on Linux for me. This is because this map is created with OpenDrive 1.1. There are differences between different versions of OpenDrive. We currently support only 1.4 version.

If you would replace all instances of `level= "0"` in Crossing8Course.xodr file to `level= "false"` then the map can be imported. They changed this attribute type at some version of OpenDrive.

**Comment by yumianhuli2** [comment]
> Are you sure you are selecting same file when importing it on Linux?
> 
> I have tried it, and it fails with same error on Linux for me. This is because this map is created with OpenDrive 1.1. There are differences between different versions of OpenDrive. We currently support only 1.4 version. Older or newer versions may or may not work, depending on contents of file.
> 
> If you would replace all instances of `level= "0"` in Crossing8Course.xodr file to `level= "false"` then the map can be imported. They changed this attribute type at some version of OpenDrive.

ok solved it ! But 
1 Why not just generate the mesh ？
2 And then How do I use this map to integrate with other parts, and what are the steps？
Thank U!

**Comment by martins-mozeiko** [comment]
Map import/export in our Simulator only deals with annotations. It does not create mesh as that can be very complex process depending on precision or quality requirements.

In simplest case you could create flat plane and use it as road.
