### ISSUE TITLE
Include Parking Spaces in OpenDrive exports

### ISSUE THREAD

**Issue by Roman-jj** [lgsvl/simulator#540]
Hi, apparently the available OpenDrive maps only include lanes and junctions, no parking spaces or similar objects.

Is there any timeline on when this feature will be included? I looked at Lanelet2MapExporter.cs and OpenDriveMapExporter.cs and I could try to port the feature myself, but since you're already working on OpenDrive integration I wondered if it will be available in an upcoming release.
Or do you know of any Open Source tool to convert OSM to XODR format?

There's another issue with importing Apollo 5 HD maps, caused by lines 69 and 102 in MapImport.cs comparing old strings. The correct line should be
`if (importFormats[Selected] == "Apollo 5 HD Map")`

**Comment by martins-mozeiko** [comment]
Currently we are not working on adding parking spaces to OpenDrive exporter. I don't think we have plans to do that soon. Any contribution for this is welcomed.

I'm not aware of any converters between hdmap formats.

MapImport.cs should be already fixed in latest master. Try pulling latest source code.
