### ISSUE TITLE
How to change frequency of main camera

### ISSUE THREAD

**Issue by clepz** [lgsvl/simulator#573]
Hello,
I need to change frequency of main camera. How can I do that? I tried to change fps in json but nothing happened. It is always publishing at 10hz

**Comment by OutOfCage** [comment]
Maybe the sensor script uses `Update` to publish message and upper frequency limit is 10HZ.  You can try to change `Update` to `FixedUpdate`.  I suggest you can have a look at [Unity Time](https://docs.unity3d.com/ScriptReference/Time.html) before you do some change.

**Comment by martins-mozeiko** [comment]
Because camera rendering is using GPU, its publishing frequency will be affected of graphics performance of Simulator. Make sure they frames-per-second metric for our Simulator on your machine is reasonably high - 40 or 50 at least. Only then you'll be able to get higher camera publishing frequency.

**Comment by clepz** [comment]
@martins-mozeiko I have 1080ti. It's at 10 hz anyway.

**Comment by martins-mozeiko** [comment]
What framerate do you get for main view of simulator?

You should try running with as simple as possible configuration to eliminate other potential performance bottlenecks - try running SingleLaneRoad map with vehicle that has only Camera sensor + vehicle control sensor. Remove all other Camera or Lidar sensors. Then check the publishing rate.
