### ISSUE TITLE
Static game object settings in MAP assetbundle

### ISSUE THREAD

**Issue by riveranb** [lgsvl/simulator#685]
Unity allows us to set some static setting (batching static/lighting static/navigation static/collider static/....) for some optimization purposes.
But When I ran simulator in Unity editor play mode, I found that everything is set as non-static. Seems like all game object static settings are cleared during building assetbundle.
I'm not very familiar with HDRP, does this way I can still expect Unity to do static-wise optimization as usual? (like batching static/collider static/....)
Or what should I do to keep static game object settings in assetbundle ?

**Comment by EricBoiseLGSVL** [comment]
@riveranb We were not aware that Unity was clearing these settings.  It should be saved in the meta data.  We will look into this.  It shouldn't effect too much in the meantime.  We don't use static batching because it conflicts with GPU instancing, which gives a better performance boost.  Navigation static is for building nav meshes and not needed after they are created and static colliders are for rigidbody settings.
