### ISSUE TITLE
Graphic card inquiry

### ISSUE THREAD

**Issue by clonatron** [lgsvl/simulator#689]
Hello. I'm planning to setup a simulation environment with two machines, one running linux for apollo and one Windows for LGSVL; I have read in the Apollo git that it doesn't support Titan architectures, and in the requirements it is only shown that a dedicated Nvidia card is required. First, I'd like to know if there are more specific requirements for that card, besides the architecture: information about the memory would be highly appreciated.
Regarding the Windows machine I'm about to setup, I'd like to know if the restriction regarding the graphic card architecture is held as well: is it mandatory to have the 1080 graphic card? or it is just necessary to have the 8+ GB Nvidia card?
All information regarding the mandatory requirements will be highly appreciated!

**Comment by EricBoiseLGSVL** [comment]
@clonatron 
Yes, Apollo does not support Volta and Turing architecture GPUs (Titan V and RTX GPUs
Windows running simulator requires at least 8gb.  The more powerful the better though.  Since you are running Apollo on another machine it will help.  Keep in mind the larger and more complex the map, the more ram is needed.  Hope this helps
