### ISSUE TITLE
Created new camera sensors, the whole UI is overbright.

### ISSUE THREAD

**Issue by dr563105** [lgsvl/simulator#735]
I created three camera sensor nodes - left, main and right adjusting the **x** variable as 0, -1 and +1 in transform sensor. In the vehicles tab I used ROS2 as bridge type and these as sensor parameters. 

`[{"type": "Color Camera", "name": "Main Camera",
            "params": {"Width": 1920, "Height": 1080, "Frequency": 15, "JpegQuality": 75, "FieldOfView": 50, "MinDistance": 0.1, "MaxDistance": 1000, "Topic": "/simulator/camera_node/main/image/compressed", "Frame": "main_camera"},
            "transform": {"x": 0,** "y": 1.7, "z": -0.2, "pitch": 0, "yaw": 0, "roll": 0}},{"type": "Color Camera", "name": "Left Camera",
            "params": {"Width": 1920, "Height": 1080, "Frequency": 15, "JpegQuality": 75, "FieldOfView": 50, "MinDistance": 0.1, "MaxDistance": 1000, "Topic": "/simulator/camera_node/left/image/compressed", "Frame": "left_camera"},
            "transform": {"x": -1**, "y": 1.7, "z": -0.2, "pitch": 0, "yaw": 0, "roll": 0}},{"type": "Color Camera", "name": "Right Camera",
            "params": {"Width": 1920, "Height": 1080, "Frequency": 15, "JpegQuality": 75, "FieldOfView": 50, "MinDistance": 0.1, "MaxDistance": 1000, "Topic": "/simulator/camera_node/right/image/compressed", "Frame": "right_camera"},
            "transform": {"x": 1**, "y": 1.7, "z": -0.2, "pitch": 0, "yaw": 0, "roll": 0}},{"type": "Keyboard Control", "name": "Keyboard Car Control"},{"type": "Vehicle Control", "name": "Autoware Car Control",
            "params": {"Topic": "/vehicle_cmd"} }]`

Now upon loading the simulator in WebUI, the Simulator is overbright. 

What did do wrong?
Using the latest version 2020.03. 
[Player.log](https://github.com/lgsvl/simulator/files/4524074/Player.log)

![LGSVL car bright](https://user-images.githubusercontent.com/12048684/80127602-2e8eba00-85b2-11ea-9e38-f236e46ff50d.png)

**Comment by rongguodong** [comment]
Looks like related to auto exposure. I see half of the image is dark because of shadow. So auto exposure may improve the exposure to make the whole image brighter. If you drive to somewhere with less shadow, will the whole image become less bright?

However, it should not be related to how many cameras you are using. Do you mean the image is normal if you have only one main camera, but become bright after you added left and right camera?

**Comment by dr563105** [comment]
I just tried it BorregasAve with no shadow, same behaviour. Happens when there is only one sensor. It was working fine until about 5 hours ago. I even deleted the LGSVL simulator config and loaded again. Over exposed UI greets me. It's weird. Logging off and back in also doesn't help.

**Comment by EricBoiseLGSVL** [comment]
@dr563105 How are you disabling shadows?  2020.03 has exposure post processing volumes added to give a more realistic exposure to direct sunlight.  This or screen space reflections are causing materials to reflect in shadow.  We will look into this more.

**Comment by EricBoiseLGSVL** [comment]
@rongguodong adding you and pinging Eric to look at this issue

**Comment by dr563105** [comment]
@EricBoiseLGSVL I didn't do anything apart adding those camera sensors. After raising the issue, I even reset everything and tried again. No luck. All I remember is running the sim just after adding the sensor json caused this change. 

Anyway here is new logs of 2020.03 Sim. That UI asking to choose resolution and graphic quality didn't appear despite deleting the config folder. 
[Player_2020_03.log](https://github.com/lgsvl/simulator/files/4531226/Player_2020_03.log)
 
Also attaching BorresgasAve setup screenshot. 
![LGSVL_2020_03_Exposure](https://user-images.githubusercontent.com/12048684/80251485-49852b00-8693-11ea-8512-820e625187df.png)

**Comment by ericSterner** [comment]
@dr563105 We're currently investigating some issues with Unity's Physically Based Sky. It seems that the ground tint setting might have something to do with what you are seeing in the SF map.  This still needs to be verified but I'm looking into it right now.

**Comment by ericSterner** [comment]
![Comparison](https://user-images.githubusercontent.com/49289836/80255696-4dcd2c00-8632-11ea-87c2-135ec8a4a21a.jpg)
Here's a comparison for a white ground tint (which solves some other issues we were having) and a brown tint based on Unity's default settings.

**Comment by rongguodong** [comment]
I tested in SF scene, and verified it is because of auto exposure, and having nothing to do with number of camera sensor. Even with the default JSON setting, I can see the overbright effect. I tried to rotate view point in "free view" mode, and see the UI become normal as long as the overall brightness of the screen is normal. See attached screenshots for caparison.
![Screenshot from 2020-04-24 16-10-34](https://user-images.githubusercontent.com/11858549/80263895-fc7b6780-8646-11ea-9e5b-4581c5281c1b.png)
![Screenshot from 2020-04-24 16-10-42](https://user-images.githubusercontent.com/11858549/80263896-ff765800-8646-11ea-8071-c4d2fed55ed1.png)
![Screenshot from 2020-04-24 16-11-16](https://user-images.githubusercontent.com/11858549/80263899-01d8b200-8647-11ea-826a-46ce0f8705b7.png)
![Screenshot from 2020-04-24 16-11-24](https://user-images.githubusercontent.com/11858549/80263901-04d3a280-8647-11ea-8e8b-ef7f50ba2afa.png)

**Comment by EricBoiseLGSVL** [comment]
@rongguodong @ericSterner yes, nice work on finding the issue.  If you adjust volume Physically Based Sky ground tint to black it reduces this issue.  We are looking at solutions to fix

**Comment by EricBoiseLGSVL** [comment]
@dr563105 we are currently looking at a new way to adjust lighting to reduce exposure post processing.  We hope to release this change soon

**Comment by dr563105** [comment]
Thanks @EricBoiseLGSVL .There is also another minute glitch(bug) I found when I add JSON sensor parameters, change the bridge type in the Vehicles(say Hyundai2018Nexo) tab of WebUI and momentarily when I click 'submit', the dialogue box flickers with title to "Configuration" and Bridge type to "no bridge". 

Screenshot of the behaviour - https://gfycat.com/wideeyedhopefulgenet
