### ISSUE TITLE
Conflicting sensor topic for multiple cars

### ISSUE THREAD

**Issue by Engietoday** [lgsvl/simulator#82]
I got 2 cars connected to 2 instances of rosbridge websocket with different namespaces and ports but all the sensor information are still conflicting with each other. For example the 2 cars are publishing camera feed on the same topic. 

It doesn't seem like Lidar picks up the other car as well.

Any help?

Topic list:
/bridge0/client_count
/bridge1/client_count
/odom
/points_raw
/rosout
/rosout_agg
/simulator/camera_node/image/compressed

**Comment by martins-mozeiko** [comment]
Are you connecting both rosbridge instances to same ROS master? If they are connected to different ROS masters then each of them won't know about other ROS topics, and nothing should conflict.

**Comment by Engietoday** [comment]
I believe they were both connected to the same ROS master since all this is done on a single desktop. Plus this is the launch file I used to launch the ros `bridges.

`
<launch>
  <include ns="bridge0" file="$(find rosbridge_server)/launch/rosbridge_websocket.launch">
    
    <arg name="port" value="9090" />
  </include>
  <include ns="bridge1" file="$(find rosbridge_server)/launch/rosbridge_websocket.launch">
    
    <arg name="port" value="9091" />
  </include>
</launch>`

**Comment by martins-mozeiko** [comment]
That explains the error. If you connect bridges to same ros instance/master then topic names will be the same. This won't work. Because even if you would run two Apollo or two Autoware instances they cannot run in same network - they will not have ability to distinguish which topic goes to which instance.

You need to run rosbridge instances with different ROS masters.
For ROS1 this is possible by running roscore with different ports and then using different ROS_MASTER_URI environment variable when launching rosbridge node to indicate to which master to connect.
For ROS2 this is possible by setting ROS_DOMAIN_ID environment variable to different number before launching ros bridge.

If you are using our Apollo docker container then there is another easy way - to isolate two docker network container and expose only rosbridge port host with different numbers for different instances.

We have a script [dev_multistart.sh](https://github.com/lgsvl/apollo/blob/simulator/docker/scripts/dev_multistart.sh) that launches Apollo docker container in isolated network and forwards dreamview & rosbridge ports on different numbers. You need to run it with one argument, for example `./dev_multistart.sh 1` - this means dreamview will be available on http://localhost:8881 and rosbridge on localhost:9091. Then launch other instance by replacing `1` with `2` then second dreamview & rosbridge will be available on 8882 and 9092 ports.
