### ISSUE TITLE
Point of spawn of NPCs and pedestrians

### ISSUE THREAD

**Issue by JockTokk** [lgsvl/simulator#855]
What is start point for spawn? How can I make several point of spawn in different part of SanFrancisco?

**Comment by rongguodong** [comment]
Spawn points are game objects inside the scene. It has position/rotation hard-coded there.
![image](https://user-images.githubusercontent.com/11858549/87453042-ce0e8800-c5b6-11ea-994a-1807bacf7e9e.png)

**Comment by JockTokk** [comment]
@rongguodong sorry, I forgot to clarify I'm interested in point of spawn of NPCs and pedestrians. As I know Spawninfo is point of spawn of ego.

**Comment by rongguodong** [comment]
Not only the ego. Both NPC and pedestrian use this SpawnInfo to get their spawn positions. You can refer to our examples on how to create NPC and pedestrians:
https://github.com/lgsvl/PythonAPI/blob/master/quickstart/12-create-npc-on-lane.py
https://github.com/lgsvl/PythonAPI/blob/master/quickstart/14-create-pedestrians.py

**Comment by lemketron** [comment]
The Spawninfo is for the ego vehicle as described here in the [New Environment Video Tutorial for LGSVL Simulator](https://www.youtube.com/watch?v=S0w2ahhEPbE&feature=youtu.be&t=303).

The quickstart scripts get the ego spawninfo in order to position NPCs close to the ego vehicle spawn location. Otherwise NPCs will span randomly, or can be directed to spawn at any specific location using the PythonAPI (as shown in the quickstart scripts @rongguodong mentioned above.

So to make several spawn points you need to do that using the Python API.  Otherwise, NPCs will be positioned randomly in the scene if you check the setting in the UI to request random NPC vehicles and/or pedestrians.

**Comment by eniseiskaya** [comment]
@rongguodong Hello, if I need to create a script that will spawn pedestrians and NPCs in a specific place on the map and time. Should I use the PythonAPI?

**Comment by lemketron** [comment]
> if I need to create a script that will spawn pedestrians and NPCs in a specific place on the map and time. Should I use the PythonAPI?

@eniseiskaya Yes, as noted earlier:
> You can refer to our examples on how to create NPC and pedestrians:
> https://github.com/lgsvl/PythonAPI/blob/master/quickstart/12-create-npc-on-lane.py
> https://github.com/lgsvl/PythonAPI/blob/master/quickstart/14-create-pedestrians.py

This example will show you how to set the time of day as well:
https://github.com/lgsvl/PythonAPI/blob/master/quickstart/19-time-of-day.py

Please refer to the PythongAPI docs for additional information:
https://www.lgsvlsimulator.com/docs/python-api/

**Comment by JockTokk** [comment]
@rongguodong, @lemketron thank you very much for help and for quickly responses.
