### ISSUE TITLE
Increasing the NPC traffic infront/adjacent of the ego vehicle

### ISSUE THREAD

**Issue by dr563105** [lgsvl/simulator#873]
Hey team!

I would like to increase the NPC traffic around the ego vehicle. I read in this issue -- https://github.com/lgsvl/simulator/issues/843#issuecomment-654955329, that it is done intentionally. 

I'm not using PythonAPI. So I would like to edit the code directly in Unity and build the simulator. 

My requirements -
1. Increase the number of NPCs around the EGO and constantly present. I use SF map. 
2. Increase the threshold of cars waiting at the signal. 

I use 2020.03 version as the 2020.05 exposure level is too low and dark for EGO to detect/follow a lane. 

It would be great if you can please list the steps/files to be edited, to accomplish the task. Apart from building the simulator, adding/editing files, I would say I'm still a beginner in Unity. 

Thank you.

**Comment by EricBoiseLGSVL** [comment]
@dr563105 Let me see if I can help with this.
There are a couple of places we need to edit in code and scene objects
- MapOrigin.  This has options for maps to increase NPCs.  We max this value because of fps issues.  You can increase this in code if you want.  I suggest the other changes first before changing the max
![NPCHelp0](https://user-images.githubusercontent.com/45106230/88232634-10753c00-cc2b-11ea-908b-342c47f46c4e.png)

- Next is NCPManager.cs.  Here you can remove the check for Spawnable (This checks to see if it is an edge lane of the map.  You can remove this so it uses any lane within the spawn area set in MapOrigin that follows the ego)
- Finally you can remove the isVisible check.  This checks if any sensors "see" the npc when it tries to spawn and aborts if it will be visible on spawn.
![NPCHelp1](https://user-images.githubusercontent.com/45106230/88233934-33a0eb00-cc2d-11ea-80cc-143d1b3373d7.png)

**Comment by dr563105** [comment]
Thanks Eric. I first tried with changes in NPCManager.cs, though it had increase in NPC, there were areas where there were none. Only on changing lanes, turning at an intersection, I could make the spawn happen. Sometimes that was also not happening. 

Is it possible to make more NPCs do the changing lane frequently? 

Then I increased the NPC max count in SF map origin. It originally had `20`. I raised it to `30` which is the max limit.  Tested it again. I couldn't see much difference in traffic. In certain areas in the map, certainly get more traffic than others. 
Then I changed the NPC max count in [here](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Map/MapOrigin.cs#L56). I couldn't see an improvement. 

That count is it map related or the change I did is correct? 

I'm testing for object detection and without a lot of NPCs, the NN can't learn from the images. These changes give me an improvement from the default case.

**Comment by EricBoiseLGSVL** [comment]
No problem.  Lane change is in the NPC controller code and I don't recommend changing this.  You could try to get a random index that is lane.worlpoints.length - 1 in NPCManager.cs.  This would open more places to spawn on the lanes but may have odd NPC behavior.  Then, you could reduce the size of the spawn area in MapOrigin. This would try to spawn closer to the ego.  Lastly, the traffic light timings can be adjusted with the API or in the code here.
![SignalHelp0](https://user-images.githubusercontent.com/45106230/88321101-787f5d00-ccd3-11ea-8836-6187d1e9558e.png)

**Comment by dr563105** [comment]
Thanks Eric. 

I changed the signal labels in that file. I think I'm getting good waiting time. 

Regarding changing the value, I think you meant this variable `lane.mapWorldPositions.Count` present in this line 
`var lane = mapManager.GetLane(RandomGenerator.Next(mapManager.trafficLanes.Count));` in `NPCManager.cs`. 
Which gets the value from `mapManager`. So I'm kind of lost where to initialise the value. Can you please help? 
Despite that I can say I'm getting a good NPC traffic behaviour.

**Comment by EricBoiseLGSVL** [comment]
@dr563105 Close but no, the line I am referencing is this.
![NPCHelp3](https://user-images.githubusercontent.com/45106230/88333442-1b8ca280-cce5-11ea-9181-588f8306d043.png)
This could be converted to a random index instead of 0 but you need to exclude the last index or npcs will have issues with traffic signals and stop signs.  You may even want to exclude last 2 indexes if there are > 3 waypoints.  This will let multiple npcs spawn on one lane, giving you better density. Leave the var lane as is, this makes sure you are not selecting an intersection lane that will really mess up npc behavior.

**Comment by dr563105** [comment]
Thanks again Eric. I will close this issue for now. When I have issues again, I will reopen it.

**Comment by dr563105** [comment]
I have a new requirement - is it possible to slow the NPCs way down, easily with a few changes to the code? 

I looked into the code and did some changes to NPCController, NPCLaneController and others. I made some crude hacks to see it was really possible. It was. The vehicles slowed down enough to form an envoy around ego. However, I was hit with multiple null exceptions.

**Comment by EricBoiseLGSVL** [comment]
@dr563105 I think the only way would be to adjust the speed limit on the mapLane annotation.  Sorry, we have not made this for random traffic, only API

**Comment by dr563105** [comment]
I thought so. Thanks. I finally got the hang of driving alongside NPC matching its pace. Some glorious crashes, some mad NPC driving and lots of fun.
