### ISSUE TITLE
Reading sensor data with Apollo via Cyber

### ISSUE THREAD

**Issue by VentiOvaltine** [lgsvl/simulator#895]
I am running the LGSVL simulator with Apollo 5.5 and would like to read GPS/Lidar sensor data by using CyberRT with python.

After trying the tests under apollo/cyber/python, every python files imports a module "_cyber_wrapper" which does not exist under any folder.
![image](https://user-images.githubusercontent.com/55764337/89231664-9e8de280-d59a-11ea-8f9c-bc868064fc58.png)

Are there any suggestions on how to read data and how to run the cyber tests successfully? Thank you very much!

**Comment by EricBoiseLGSVL** [comment]
@rongguodong Any idea on this?

**Comment by rongguodong** [comment]
This does not sound like a simulator question. Are you trying to run some scripts provided by Apollo and get errors? If so, maybe you want to ask at Apollo's GitHub?

**Comment by lemketron** [comment]
You also asked about this in #493, and [this comment](https://github.com/lgsvl/simulator/issues/493#issuecomment-667940122)suggested it might be an issue with cyber_py in apollo master. Please file an issue in the [apollo github issues](https://github.com/ApolloAuto/apollo/issues/). Feel free to link back here (or reference this issue in your apollo issue) so that others may locate the eventual solution.

**Comment by VentiOvaltine** [comment]
This is the issue in Apollo. https://github.com/ApolloAuto/apollo/issues/12023
