### ISSUE TITLE
Relative to which position of the car are the sensors located

### ISSUE THREAD

**Issue by dymons** [lgsvl/simulator#927]
I want to understand what position of the car model the offsets are set for sensors (Lidar, Radar, GNSS, etc.).
Let's look at the example of GNSS, where the `transform` field in the JSON file is used to set the position of sensors:
```
{
    "type": "GPS Device",
    "name": "GPS",
    "params": {
      "Frequency": 12.5,
      "Topic": "/nmea_sentence",
      "Frame": "gps",
      "IgnoreMapOrigin": true
    },
    "transform": {
      "x": 0,
      "y": 0,
      "z": 0,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    }
}
```

In the vehicles documentation page for the [Example JSON](https://www.lgsvlsimulator.com/docs/vehicles-tab/#example-json) example, I saw the following phrase (this may be the answer to my question, but I would like to clarify):

> The JSON includes a GPS sensor in the center of the vehicle that publishes data on the "/nmea_sentence" topic,  a LIDAR sensor 2.312m above the center of the vehicle that publishes data on the "/points_raw" topic, a Manual Control input which allows the keyboard input to control the car, and a Vehicle Control input which subscribes to the Autoware AD Stack control commands.

I am interested in the phrase 
> a GPS sensor in the center of the vehicle

Did I understand correctly that the sensor is located in the center of the car, on the `x` and `y` axes, not including the `z` coordinate?
Schematically I displayed this in the image:
![mazda-6-2008](https://user-images.githubusercontent.com/20445903/90953642-15215000-e476-11ea-887b-87444f5c58f8.png)

Did I understand correctly or not? If not, could you explain relative to which position of the car are the sensors located?

In advance, thank you very much for the explanation.

**Comment by EricBoiseLGSVL** [comment]
@dymons In Unity meshes are zero'd at the origin.  This is (0f, 0f, 0f).  Sensors are based off local position relative to this zero'd position.  You can run simulator and in the visualizer, enable the transform visualizer like so.
![TSHelp0](https://user-images.githubusercontent.com/45106230/91079576-12029d00-e5f9-11ea-8310-e1a660cecd86.png)

You can also see the positions when running the simulator in the editor like so.
![TSHelp1](https://user-images.githubusercontent.com/45106230/91079606-1b8c0500-e5f9-11ea-8714-bb542b42b466.png)


Finally, you can make the sensor be relative to another sensor instead of the origin like so.
![TSHelp2](https://user-images.githubusercontent.com/45106230/91079618-1f1f8c00-e5f9-11ea-91b1-ad1e0324ff83.png)


Hopefully this helps.

**Comment by dymons** [comment]
I understand thanks for the explanation!
