### ISSUE TITLE
Simulation Tab is not avalibale?

### ISSUE THREAD

**Issue by Addi2020** [lgsvl/simulator#964]
![Screenshot from 2020-09-06 18-32-37](https://user-images.githubusercontent.com/61130487/92324274-cdecaf00-f072-11ea-9d05-33f0712f69c0.png)

**Comment by EricBoiseLGSVL** [comment]
@Addi2020 This is not a clear issue.  Please post what your issue is with details on how to reproduce.  If this is referencing the Simulation menu item, you need post what errors you have in the Console panel.  I am guessing that you did not enable git lfs before you cloned the repo and you have compilation errors.

**Comment by Addi2020** [comment]
thank you, the issue is solved. (The project has some missing files, Colne or downloads the project again)
